---
title: "alignment trimming"
author: "Laura Dijkhuizen"
date: "25/04/2022"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# alignment dimensions

## import data

```{r}
setwd("~/gitprojects/ANS_phylogeny/")
library("data.table")
library(ggplot2)
all_dims <- fread(input = "data/alignments_trimmed/allignment_dimensions.tab"
                  ,header = F
                  ,col.names = c(
                    'all_name',
                    'all_algorithm',
                    'gap_threshold',
                    'res_content',
                    'seq_content',
                    'quantity',
                    'value'
                    )
                  ,stringsAsFactors = T
                  )
head(all_dims)
```


## width
```{r}
temp_df <- all_dims[(seq_content=1 & quantity == 'width' & gap_threshold != 3)]
width_heatmap <- ggplot(temp_df,
                         mapping = aes(
                           x=gap_threshold,
                           y=value
                           )
                         )
width_heatmap <- width_heatmap + geom_line()
width_heatmap <- width_heatmap + geom_point()
width_heatmap <- width_heatmap + geom_text(aes(label=value),nudge_x = 3,nudge_y = 1)
width_heatmap <- width_heatmap + theme_minimal()
width_heatmap
```


## length
Let's make a heatmap of allignment dimensions
```{r}
temp_df <- all_dims[(gap_threshold == 3 & quantity == 'length')]
temp_df$seq_content <- as.factor(temp_df$seq_content)
temp_df$res_content <- as.factor(temp_df$res_content)
length_heatmap <- ggplot(temp_df,
                         mapping = aes(
                           x=seq_content,
                           y=res_content,
                           fill=value
                           )
                         )
length_heatmap <- length_heatmap + geom_tile()
length_heatmap <- length_heatmap + geom_text(aes(label=value))
length_heatmap <- length_heatmap + theme_minimal()
length_heatmap
```


# alignment gap frequency

## import data

```{r}
setwd("~/gitprojects/ANS_phylogeny/")
library("data.table")
library(ggplot2)
all_gap <- fread(input = "data/alignments_trimmed/allignment_gap-freq.tab"
                ,header = F
                ,col.names = c(
                     'all_name',
                     'all_algorithm',
                     'gap_threshold',
                     'seq_content',
                     'res_content',
                     'gaps'
                     )
                ,stringsAsFactors = T
                ,fill = T
                )
head(all_gap)
```

## gap freq

```{r}
temp_df <- all_gap[res_content>=95]
temp_df$seq_content <- as.factor(temp_df$seq_content)
temp_df$res_content <- as.factor(temp_df$res_content)
gap_dist_plot <- ggplot(temp_df,
                         mapping = aes(
                           x=gaps,col=seq_content
                           )
                         )
gap_dist_plot <- gap_dist_plot + facet_grid(seq_content ~ res_content)
gap_dist_plot <- gap_dist_plot + geom_freqpoly(binwidth=10)
gap_dist_plot <- gap_dist_plot + theme_minimal()
gap_dist_plot
```


```{r}
gap_dist_plot <- ggplot(temp_df,
                         mapping = aes(
                           x=gaps,
                           col=seq_content,
                           fill=seq_content
                           )
                         )
gap_dist_plot <- gap_dist_plot + facet_grid( ~ res_content)
gap_dist_plot <- gap_dist_plot + geom_freqpoly(binwidth=10)
gap_dist_plot <- gap_dist_plot + theme_minimal()
gap_dist_plot
```



```{r}
gap_dist_plot <- ggplot(temp_df,
                         mapping = aes(
                           x=gaps,fill=res_content,
                           col=res_content
                           )
                         )
gap_dist_plot <- gap_dist_plot + facet_grid( ~ seq_content)
gap_dist_plot <- gap_dist_plot + geom_freqpoly()
gap_dist_plot <- gap_dist_plot + theme_minimal()
gap_dist_plot
```



```{r}


gap_dist_plot <- ggplot(temp_df[(
                                 (seq_content == .5 & res_content == 99 ) | 
                                 (seq_content == .75 & res_content == 98 ) | 
                                 (seq_content == .5 & res_content == 95 )
                                 )],
                         mapping = aes(
                           x=gaps,fill=res_content,
                           col=res_content
                           )
                         )
gap_dist_plot <- gap_dist_plot + geom_freqpoly()
gap_dist_plot <- gap_dist_plot + theme_minimal()
gap_dist_plot
```
